version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "zsquare_web"
        command: uvicorn app:app --host 0.0.0.0 --port 8001
        volumes:
            - ./app:/app
        ports:
            - "8001:8001"
        env_file:
            - .env
        restart: always
