version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "zsquare_form_web"
        command: uvicorn app:app --host 0.0.0.0 --port 8000
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always
